import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@src/components/Navbars/navbar";
import Footer from "@src/components/layout/footer";
import ScrollButton from "@src/components/scrollButton";

export const metadata: Metadata = {
  title: "Onehub Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
        <ScrollButton />
      </body>
    </html>
  );
}
